### ISSUE TITLE
Out of place dense emerald and dense gold ores 1.19.2

### ISSUE THREAD

**Issue by SillyGoblin** [NewJumper/DenseOres#1]
You have dense ores that aren't behaving like their vanilla counterparts as expected.
Emeralds normally are suppose to generate only in mountain biomes and their sub biome variants, but the dense variant spawns in biomes it's not expected to be in.
Gold normally generate between y-64 through y32, but the dense variant generates above that threshold very consistently in my testing.

This issue has been tested on forge 43.2.3
The mod version that I used being 1.19.2-1.2.0.

Pictures:

Emerald in a plains biome with debug menu for information.
![emerald_in_plains_bottom](https://user-images.githubusercontent.com/78075413/221390729-f1ae1e1e-9caa-4a08-bf76-6db2c7f2d5ef.png)

To show that it is a plains biome just above the previously shown picture, mostly showing because in my experience minecraft tags their caves weirdly.
![emerald_in_plains_top](https://user-images.githubusercontent.com/78075413/221390737-8a9cb030-c1c1-4cc0-87dc-b91ccba3591c.png)

Both gold and emerald being very out of place, windswept savannas are not suppose to generate emeralds last I checked and the gold is 63 blocks above where its expected to be.
![out_of_place_gold_and_emerald](https://user-images.githubusercontent.com/78075413/221390811-f6a624b6-f83c-43f9-89d2-9808383f55a9.png)

Thank you for your time with this mod, it is something I've been for looking for with the modpack I'm working on.
Thought you should know about this issue.

**Comment by NewJumper** [comment]
The dense emerald generation was an oversight by me, but the dense gold generation was intentional. However, it may be best that dense gold generates within the threshold of vanilla gold ores. Good shout, thanks.

**Comment by NewJumper** [comment]
- dense emerald ores only generate in mountain biomes now
- made dense gold ores more common in badlands biomes
- fixed dense gold y-level generation
