### ISSUE TITLE
Crash wen create new World

### ISSUE THREAD

**Issue by ElardHuaraca** [NewJumper/DenseOres#2]
**Description**
Problem when create new worl in single player, mod load normally in menu but wen create new world throw this error "Unbound values in registry ResourceKey"

**Steps To Reproduce**
1. Go to 'Minecraft single player'
2. Try 'generate new world'
3. Boom, error

**Additional context**
I got to see the same problem in other mods it seems to be a bug with the new version of minecraft 1.19.3

**Screenshots**
![imagen](https://user-images.githubusercontent.com/56555556/224580561-5140fb49-6b29-4fb1-978d-5fed5711653b.png)

**Comment by NewJumper** [comment]
Are there any other mods you were playing with?

**Comment by ElardHuaraca** [comment]
Yes, but this error is for update minecraft 1.19.3-44.1.2. I report the same bug in another mod

**Comment by NewJumper** [comment]
It seems to be related to world generation changes in 1.19.3, do you know if the other mod has fixed the issue? If you could link the bug report that would be amazing.

**Comment by NewJumper** [comment]
Fixed in 1.19.4
